name: Docs Deployment

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      # 1. 设置 Node.js 22.11.0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"
          cache: 'pnpm'

      # 2. 安装 pnpm (使用官方 pnpm action)
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      # 3. 设置 PATH (正确方式)
      - name: Add pnpm to PATH
        run: |
          echo "$(npm prefix -g)/bin" >> $GITHUB_PATH
          echo "PATH: $PATH"

      # 4. 验证 pnpm
      - name: Verify pnpm
        run: |
          pnpm -v
          which pnpm

      # 5. 缓存配置
      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm-store
            ​**/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # 6. 安装依赖
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm store prune

      # 7. 构建项目
      - name: Build VuePress site
        run: pnpm run docs:build

      # 8. 部署
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
          publish_branch: gh-pages
          force_orphan: true
