name: Docs Deployment

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. 设置 Node.js 22.11.0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"
          cache: 'pnpm'

      # 2. 显式安装 pnpm
      - name: Install pnpm
        run: |
          npm install -g pnpm@8
          echo "PNPM version: $(pnpm -v)"
          echo "PATH: $PATH"
          echo "which pnpm: $(which pnpm)"

      # 3. 设置 PATH 确保能找到 pnpm
      - name: Setup PATH
        run: |
          echo "$(npm prefix -g)/bin" >> $GITHUB_PATH
          echo "Updated PATH: $PATH"

      # 4. 恢复缓存
      - name: Restore pnpm cache
        uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm-store
            ​**/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # 5. 安装依赖
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm store prune

      # 6. 构建项目
      - name: Build VuePress site
        run: pnpm run docs:build

      # 7. 部署
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
          publish_branch: gh-pages
          force_orphan: true
