name: Docs Deployment

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      # 设置全局环境变量
      PNPM_HOME: /usr/local/bin
      PATH: ${{ env.PNPM_HOME }}:${{ env.PATH }}

    steps:
      - uses: actions/checkout@v4

      # 1. 设置 Node.js 22.11.0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.11.0"
          cache: 'pnpm'

      # 2. 安装 pnpm (显式指定版本和安装位置)
      - name: Install pnpm
        run: |
          npm install -g pnpm@8 --prefix /usr/local
          echo "pnpm path: $(which pnpm)"
          echo "pnpm version: $(pnpm -v)"
          echo "PATH: $PATH"

      # 3. 验证 pnpm 可用性
      - name: Verify pnpm
        run: |
          if ! command -v pnpm &> /dev/null; then
            echo "::error::pnpm command not found!"
            exit 1
          fi
          pnpm -v

      # 4. 缓存配置
      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm-store
            ​**/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # 5. 安装依赖
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm store prune

      # 6. 构建项目
      - name: Build VuePress site
        run: pnpm run docs:build

      # 7. 部署
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
          publish_branch: gh-pages
          force_orphan: true
