name: Deploy Docs

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 7.33.2  # 使用与 lockfile 兼容的版本

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build Packages
        run: pnpm docs:build

      - name: Docs build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm docs:build

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 改用 token 参数
          branch: dist-pages
          folder: src/.vuepress/dist
          single-commit: true
          clean: true  # 可选：部署前清理目标分支
          force: true  # 可选：强制推送